name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.7.0'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run Rubocop (format check)
      run: bundle exec rubocop --parallel
  coverage:
    needs: [rubocop]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run RSpec (test & coverage)
      uses: paambaati/codeclimate-action@v5.0.0
      env:
        CC_TEST_REPORTER_ID: a5336c00a7f3945375dbf7c7912f373ac1b7571966cf1aa935aa407e316a7641
      with:
        coverageCommand: bundle exec rspec
        coverageLocations: ${{ github.workspace }}/coverage/coverage.json:simplecov
        debug: true
